name: Release Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get short SHA
      id: vars
      run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

    - name: Create Windows artifact
      run: |
        cd windows
        zip -r ../elcap-deps-windows-${{ steps.vars.outputs.short_sha }}.zip .
        cd ..

    - name: Create Linux artifact
      run: |
        cd linux
        tar -czf ../elcap-deps-linux-${{ steps.vars.outputs.short_sha }}.tar.gz .
        cd ..

    - name: Create MacOS artifact
      run: |
        cd macos
        zip -r ../elcap-deps-macos-${{ steps.vars.outputs.short_sha }}.zip .
        cd ..

    - name: Create and upload release
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: release-${{ steps.vars.outputs.short_sha }}
        name: elcap-deps-${{ steps.vars.outputs.short_sha }}
        draft: false
        prerelease: false
        files: |
          ./elcap-deps-windows-${{ steps.vars.outputs.short_sha }}.zip
          ./elcap-deps-linux-${{ steps.vars.outputs.short_sha }}.tar.gz
          ./elcap-deps-macos-${{ steps.vars.outputs.short_sha }}.zip
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
